### PR TITLE
Add Microsoft

### PR DESCRIPTION
**Pull request by Zhiyu-Lei**

### CODE REVIEW

**Review by Syphinx — APPROVED** [review]

**Comment by vikram-10** [comment]
image

**Comment by vikram-10** [comment]
image

**Comment by vikram-10** [comment]
Not exactly sure if they qualify as new-grad roles

**Review by preethamcoder — APPROVED** [review]

**Comment by harshkpatel2002** [comment]
This isn’t new grad. Posting like this have been in and out for a while On Oct 3, 2023, at 7:19 PM, Preetham Thelluri ***@***.***> wrote:﻿
@preethamcoder approved this pull request.

**Pull request closed without merging**
