### PR TITLE
Add Bloomberg SWE

### PR DESCRIPTION
**Pull request by daykills**
Add Bloomberg SWE

### CODE REVIEW

**Comment by Manav-Ram19** [comment]
any idea when they're gonna open up?

**Comment by Mazzaleen** [comment]
> any idea when they're gonna open up?

Early September perhaps
Or late aug

**Comment by rohan12k** [comment]
> Add Bloomberg SWE

it would be easy if you provide him the job link also.

**Comment by Mazzaleen** [comment]
It hasnt opened yet. See here: https://careers.bloomberg.com/job/search?el=Students+and+Recent+Graduates&qf=engineering&mpam-page=MPAM-blog-post&tactic-page=589375&_ga=2.145123892.1428388086.1690249753-328550462.1688595312&_gl=1*24kucg*_ga*MzI4NTUwNDYyLjE2ODg1OTUzMTI.*_ga_F61D775DS4*MTY5MDI0OTc1Mi4xLjEuMTY5MDI0OTc5OS4xMy4wLjA.

**Comment by iTvX** [comment]
https://github.com/ReaVNaiL/New-Grad-2024/assets/46791134/5077bfee-66d1-4171-8186-16270e39579d

**Comment by iTvX** [comment]
https://github.com/ReaVNaiL/New-Grad-2024/assets/46791134/60aa6e8a-9b0c-4da3-bbde-4e03e86210ee

**Comment by ReaVNaiL** [comment]
Closing the CR until they open.

**Comment by casnz1601** [comment]
not helpful

**Pull request closed without merging**
