### PR TITLE
Add Paypal's opening

### PR DESCRIPTION
**Pull request by SoumyaMukhija**

### CODE REVIEW

**Review by sud298 — APPROVED** [review]
Link is working and work authorization is required.

**Comment by SoumyaMukhija** [comment]
How do we merge this?

**Comment by pratikgehlott** [comment]
can people on OPT apply?

**Comment by SoumyaMukhija** [comment]
> can people on OPT apply?

I don't think so.

**Comment by SoumyaMukhija** [comment]
> It only says "Must be able to obtain authorization to work in the U.S." so I think opt is allowed no?

I am not entirely sure.

**Comment by sud298** [comment]
Yes you can apply if you've EAD too.

**Comment by sud298** [comment]
> How do we merge this?

Someone with write permission should merge this. How to know who has it?

**Comment by Avimehta14** [comment]
Yes, OPT is allowed, they do hire CPT/OPT students

**Comment by dirt1de** [comment]
> How do we merge this?

I think only @ReaVNaiL can do it.

**Comment by pj323** [comment]
Yes, Paypal Provides Sponsorhip. There are also some Intern SW roles available. [https://paypal.eightfold.ai/careers?query=R0106013&pid=274895391783&domain=paypal.com&sort_by=relevance](url)

**Comment by SoumyaMukhija** [comment]
> Yes, Paypal Provides Sponsorhip. There are also some Intern SW roles available. [https://paypal.eightfold.ai/careers?query=R0106013&pid=274895391783&domain=paypal.com&sort_by=relevance](url)

The link doesn't work for me.

**Comment by pj323** [comment]
Try this https://www.linkedin.com/jobs/search/?currentJobId=3684987059&f_C=1482&originToLandingJobPostings=3684987057%2C3684983622%2C3684982997%2C3684985311%2C3684987059%2C3684981950%2C3679670363

**Comment by kingsotn** [comment]
this seems a little sus what is eightfold.ai?

**Comment by SoumyaMukhija** [comment]
> this seems a little sus what is eightfold.ai?

According to Google, 

> Eightfold's Talent Intelligence Platform is a diverse AI recruitment tool and includes: Talent Acquisition: Hire for all roles with a single source-to-offer solution that attracts more qualified talent and closes candidates faster.

**Review by ReaVNaiL — APPROVED** [review]

**Pull request merged**
