### PR TITLE
Add WeRide.ai Software Engineer - New Grads 2024

### PR DESCRIPTION
**Pull request by dirt1de**

### CODE REVIEW

**Comment by Kunal301** [comment]
Can someone please tell me how to do this
Firstly I am confused that if a task is saying to add a company
how do I get the company details like the link, location and all
if i have the info then i can add it to the readme file

**Comment by dirt1de** [comment]
> Can someone please tell me how to do this Firstly I am confused that if a task is saying to add a company how do I get the company details like the link, location and all if i have the info then i can add it to the readme file

What do you mean? Are you confused about how to do the pull request or something else?

**Comment by Kunal301** [comment]
Like if I get a mail about adding PayPal
So how to approach it 
like i read the file "how to contribute"
and i have also forked the repo but to do changes in readme , I need the info like
the link of the company, location and all, then I can make the changes 
How to get all of this as in mail there is not any info provided or I am missing something?

**Comment by dirt1de** [comment]
Well, you can always search for these on the company's career page. I don't know if this answers your question.

**Comment by Kunal301** [comment]
I think you didn't understand my question
basically, i want to contribute to this repo
But I am not able to do so 
Whenever I get a mail there is already someone who has committed to the task
Ok if you can just tell me If I want to contribute what and how can I do

**Comment by dirt1de** [comment]
To find the link to new job openings, you just have to browse on LinkedIn or whatever job boards.

**Comment by dirt1de** [comment]
Yes. All the information needs to be typed manually based on the job description.

**Review by ReaVNaiL — APPROVED** [review]

**Pull request merged**
