### PR TITLE
Add L3Harris Software Engineer, Masters New Grad

### PR DESCRIPTION
**Pull request by Divya6696**
Job Link: https://careers.l3harris.com/job/-/-/4832/52541962560?src=SNS-10240

### CODE REVIEW

**Comment by Mazzaleen** [comment]
Anyone actually hear back from l3harris technologies? They have had listed jobs for new grads in an abundance of locations for weeks now and they keep reposting, my guess is that it has to be some sort of phishing or closed role because that's awfully suspicious

**Comment by Divya6696** [comment]
Wow really? Apologies, I wasn't aware. I thought, since they had come to our university once, that they'd be legit. 🤔 But yes, if it's like you said, then @ReaVNaiL please don't post it, so as to not mislead others. 🥺

**Comment by Mazzaleen** [comment]
Its just my personal experience so i defintely might be wrong- It is a known company anyway>

 but i feel like they're just doing that thing where thye just open apps for the sake of opening them without any intention to hire anyone (these new grad postings have been reposted on on all through out this summer)

**Comment by rohan12k** [comment]
Same thing is with Synopsys Inc.

**Comment by ReaVNaiL** [comment]
They seem to have taken down a few of the job postings. The link provided no longer works.

**Pull request closed without merging**
