### PR TITLE
Added Chevron FT Roles and edited Lockheed Martin posting

### PR DESCRIPTION
**Pull request by hvnguyen57**
Feel free to edit accordingly :)

### CODE REVIEW

**Comment by nguyenvothuan** [comment]
Its not a requirement tho so I think its still an option.
*Vo Thuan Nguyen*
Student

High School For The Gifted - VNU
153 Nguyen Chi Thanh, District 5, HCM City
t: 0907-501-946
e: ***@***.***
[image: Facebook icon] <https://www.facebook.com/CodeTwo>   [image:
LinkedIn icon] <https://www.linkedin.com/company/codetwo>   [image: Twitter
icon] <https://twitter.com/CodeTwoSoftware>   [image: Google Plus icon]
<https://plus.google.com/+CodeTwoSoftware>   [image: Youtbue icon]
<https://www.youtube.com/user/CodeTwoChannel>

**Comment by zzjharry-upenn** [comment]
For Microsoft, it seems that the job post is just for one single SDE, and it is not listed under "Students and Graduates". Hence, it's probably not a new grad role.

**Comment by zspherez** [comment]
This should not be merged while Microsoft is still in the PR. This is not a university position, meaning you must have graduated at least a year ago to be eligible for the position. Also like @zzjharry-upenn mentioned, this is a post for a single position, not a general new grad app.

**Review by aseemsharma55 — CHANGES_REQUESTED** [review]
For the chevron role, it mentions, _**Chevron regrets that it is unable to sponsor employment visas for this position. To be considered for this position, applicants must be legally authorized to work in the United States as a U.S. citizen or national, asylee, refugee, or lawful permanent resident.**_

**Comment by hvnguyen57** [comment]
Ok, the changes made should be good now. 
-corrected citizen/visa requirements for chevron
-removed microsoft posting
-edited LM posting since no longer available

**Review by ReaVNaiL — APPROVED** [review]

**Pull request merged**
