### PR TITLE
Add Cisco SDE I, II

### PR DESCRIPTION
**Pull request by li-minhao**

### CODE REVIEW

**Comment by pavan3008** [comment]
Looks like it needs work authorization -- "Able to legally live and work in the country for which you’re applying, without visa support or sponsorship"

**Review by ReaVNaiL — APPROVED** [review]

**Review by ReaVNaiL — APPROVED** [review]

**Comment by casnz1601** [comment]
> Looks like it needs work authorization -- "Able to legally live and work in the country for which you’re applying, without visa support or sponsorship"

You may add "No sponsorship" in the "Citizenship/Visa Requirements" Column.

**Comment by ReaVNaiL** [comment]
Let's add the requirements before merging the PR.

**Comment by li-minhao** [comment]
@ReaVNaiL Updated

**Review by ReaVNaiL — APPROVED** [review]

**Pull request merged**
