### PR TITLE
Added IXL NewGrad SWE.md

### PR DESCRIPTION
**Pull request by aaron3alexander**

### CODE REVIEW

**Review by Aryan-Dang — APPROVED** [review]
Looks good!

**Review by oubotong — APPROVED** [review]
LGTM

**Review by kingsotn — COMMENTED** [review]
lgtm

**Comment by ashwin2000** [comment]
This doesn't mention 2024 but is it safe to assume it is just for 2024 and not for recent graduates?

**Comment by aaron3alexander** [comment]
> This doesn't mention 2024 but is it safe to assume it is just for 2024 and not for recent graduates?

Yeah, this repo is for 2024 new grads

**Comment by ashwin2000** [comment]
No I mean the posting doesn't mention 2024

**Comment by aaron3alexander** [comment]
> No I mean the posting doesn't mention 2024

Ohh I see, you're right. I just assumed that they were referring to 2024 graduates but that's a mistake on my part. The post is probably for recent graduates, good catch.

**Comment by park-jemin** [comment]
I'm a 2023 grad that received an offer through this an hour ago - just confirmed with the university recruiter that this is open to both 2023 and 2024 grads, but 2023 grad hiring is about to close up soon

**Review by ReaVNaiL — APPROVED** [review]

**Pull request merged**
