### PR TITLE
Added Two New Grad roles

### PR DESCRIPTION
**Pull request by Sumer16**
These companies are hiring New Grads:
- Loop
- Crusoe

### CODE REVIEW

**Review by ggopalai — CHANGES_REQUESTED** [review]
Loop is 2023 NG.

**Comment by Sumer16** [comment]
Still it is a new grad and they are still hiring for this role.

**Comment by ggopalai** [comment]
This repo is for 2024 NG :)

**Comment by hvnguyen57** [comment]
lgtm

**Review by hvnguyen57 — APPROVED** [review]

**Pull request merged**
