### PR TITLE
Add Mathematica and add a role to BlackRock

### PR DESCRIPTION
**Pull request by mtlogs**
1) Add Mathematica
2) Add BlackRock's Associate Software Engineer, Application Engineer role

### CODE REVIEW

**Comment by Mazzaleen** [comment]
Mathematica isn't SWE - Black role requires two years of experience

**Review by Mazzaleen — CHANGES_REQUESTED** [review]
Mathematica isnt' SWE- Black rock requires two years of experience

**Comment by mtlogs** [comment]
Hi @Mazzaleen ! Thanks for the flag. Didn't catch that with BlackRock! Will be sure to remove. I figured Mathematica's role works because there's a degree of data science involved (they mention Data Science and Computer Science are relevant majors for the role)

**Comment by mtlogs** [comment]
I removed the Blackrock role!

**Comment by ReaVNaiL** [comment]
I'll merge it once a few more approvals go through, it doesn't look like a new grad 2024 pipeline listing but I guess I'll consider it since it's 0 YoE.

**Pull request closed without merging**
