### PR TITLE
update Delta Airline

### PR DESCRIPTION
**Pull request by leo880714**

### CODE REVIEW

**Review by KaiserZZK — COMMENTED** [review]
Hi! I couldn't seem to the info on the position page itself; could you provide the source if possible--appreciate it :^)

**Comment by leo880714** [comment]
Yeah. I do not find the info as well. But its an instant rejection after apply. So I guess.

**Comment by shihjames** [comment]
I got rejected right after I applied too

**Comment by ericyu0510** [comment]
instant rejection as well

**Comment by KaiserZZK** [comment]
Thanks for the update! Approving the PR rn

**Review by KaiserZZK — APPROVED** [review]

**Pull request merged**
