### PR TITLE
Add RemoTasks QA Engineer role

### PR DESCRIPTION
**Pull request by OKLabsTalent**
OKLabs has partnered with Remotasks to handle their recruiting and onboarding pipelines.

### CODE REVIEW

**Review by nelson123-lab — APPROVED** [review]

**Comment by harshkpatel2002** [comment]
This isn’t a new grad role, it’s a remotask scam posting.On Mar 17, 2024, at 3:05 PM, OKLabsTalent ***@***.***> wrote:﻿OKLabs has partnered with Remotasks to handle their recruiting and onboarding pipelines.



You can view, comment on, or merge this pull request online at:
  https://github.com/ReaVNaiL/New-Grad-2024/pull/550

Commit Summary

  96005cd  Add RemoTasks QA Engineer role


File Changes  (1 file)

  
    M
    README.md
    (1)
  


Patch Links:

  https://github.com/ReaVNaiL/New-Grad-2024/pull/550.patch
  https://github.com/ReaVNaiL/New-Grad-2024/pull/550.diff

**Review by harshkpatel2002 — CHANGES_REQUESTED** [review]
Remove

**Comment by ajkraus04** [comment]
Plenty of engineers are making a lot of money using remotasks. Remotasks is the platform scale AI uses to do RLHF for all their partners. If it was a scam - then Open AI, Google's Bard, etc would all be getting duped.

**Review by ethanlaj — CHANGES_REQUESTED** [review]
Scam

**Comment by harshkpatel2002** [comment]
This for new grad postings. I wouldn’t consider remotasks the intended purpose of this repo. This is for full time postings, not contract work. On Mar 17, 2024, at 3:26 PM, Andrew Kraus ***@***.***> wrote:﻿
Plenty of engineers are making a lot of money using remotasks. Remotasks is the platform scale AI uses to do RLHF for all their partners. If it was a scam - then Open AI, Google's Bard, etc would all be getting duped.

**Comment by tim-oteoo** [comment]
I am on the QA team and I make $55 an hour through Remotasks this is not a scam. I've been here since mid-2023. I thought this was a scam too, but it is not. I love it.

**Comment by tim-oteoo** [comment]
> This for new grad postings. I wouldn’t consider remotasks the intended purpose of this repo. This is for full time postings, not contract work. On Mar 17, 2024, at 3:26 PM, Andrew Kraus ***@***.***> wrote:﻿ Plenty of engineers are making a lot of money using remotasks. Remotasks is the platform scale AI uses to do RLHF for all their partners. If it was a scam - then Open AI, Google's Bard, etc would all be getting duped. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

This is a great opportunity for people to work up to and above 40hrs a week in development. The market is awful, don't steer people away from a legitimate opportunity.

**Comment by ethanlaj** [comment]
Not sure if you'll have much luck. Doesn't seem legit at all. One was closed previously for the same reason...

https://github.com/ReaVNaiL/New-Grad-2024/pull/547

**Comment by harshkpatel2002** [comment]
I wouldn't want to deter people from legitimate opportunities. I am still looking myself, but there are numerous red flags with this commit. 

1. The GitHub account used to create this commit was created 6 minutes prior to this change being updated.

2. Previously we have removed a remotask "job" on here because it was marked as a scam.

**Comment by vns9** [comment]
It's a scam posting.

**Pull request closed without merging**
