### PR TITLE
Shortbread AI Full Stack Founding Engineer

### PR DESCRIPTION
**Pull request by evanhu1**

### CODE REVIEW

**Review by KaiserZZK — APPROVED** [review]

**Comment by ReaVNaiL** [comment]
@evanhu1 Out of curiosity it's labeled as New Grad, but it requires 3+ YoE, would you be able to confirm they are hiring New Grads?

**Comment by evanhu1** [comment]
Yes, I'm the hiring manager for the role, we are also open to New Grads

**Comment by wadhwahitesh** [comment]
@evanhu1  Would you hire new grads though? 

If you are going to, then I should be given a call back as my resume matches perfectly with the JD.

But I don't think that's going to happen because why will anyone hire a new grad if they can get 3+ yoe people for the same salary?

[Hitesh_Wadhwa_resume_GenAI.pdf](https://github.com/ReaVNaiL/New-Grad-2024/files/15256993/Hitesh_Wadhwa_resume_GenAI.pdf)

**Comment by evanhu1** [comment]
@ReaVNaiL Could you please update the sponsorship section to say We are open to sponsoring OPT candidates for a work visa? Thank you. I can also open a new pr

**Comment by evanhu1** [comment]
> @evanhu1 Would you hire new grads though?
> 
> If you are going to, then I should be given a call back as my resume matches perfectly with the JD.
> 
> But I don't think that's going to happen because why will anyone hire a new grad if they can get 3+ yoe people for the same salary?
> 
> [Hitesh_Wadhwa_resume_GenAI.pdf](https://github.com/ReaVNaiL/New-Grad-2024/files/15256993/Hitesh_Wadhwa_resume_GenAI.pdf)

We would hire an exceptional new grad. Your resume looks like a good fit, but I don't see your application in the system

**Comment by anchalg00** [comment]
Hi @evanhu1 I recently hit the maximum number of applications on YC Combinator. Thus, not sure if you can receive my application there. 
[AnchalGupta_Resume.pdf](https://github.com/ReaVNaiL/New-Grad-2024/files/15257598/AnchalGupta_Resume.pdf)
Would you please take a look at my resume? 
I have worked with Expedia and Amazon Robotics as a Software Engineer. I have had the opportunity to work extensively with technologies such as Java, JavaScript, TypeScript, Node.js, Angular, Spring Boot, AWS, Docker, Ci/CD, and infrastructure. I am confident in my ability to adapt quickly to new technologies and frameworks, making me a versatile asset to any team. I feel like I could be a great fit!

**Pull request merged**
