### PR TITLE
Add Elekta Software Development Engineer

### PR DESCRIPTION
**Pull request by faiyazthulla-shaik**

### CODE REVIEW

**Review by kuscholar — APPROVED** [review]

**Comment by ujjwalm29** [comment]
Does this specifically mention "new grad". I did a search https://elekta.wd3.myworkdayjobs.com/en-US/Elekta_Careers/details/Software-Development-Engineer_R2023-1243?q=software&Location_Country=bc33aa3152ec42d4995f4791a106ed09 .

Can't find new grad mention.

**Comment by faiyazthulla-shaik** [comment]
Hi,

This is a entry level position and doesn't require any work experience. You can verify this on LikendIn.

**Comment by ashwin2000** [comment]
It doesn't specify that it is for 2024 grads, so it probably is for immediate joiners, right?

**Comment by faiyazthulla-shaik** [comment]
Ohh!! My bad!! Yes, this is for immediate joining.

**Comment by faiyazthulla-shaik** [comment]
Can I go ahead and close this request.

**Pull request closed without merging**
