### PR TITLE
Add Zoom

### PR DESCRIPTION
**Pull request by KaiserZZK**

### CODE REVIEW

**Comment by KaiserZZK** [comment]
Never mind; didn't see in job req that "**Masters Degree or PhD** in engineering fields such as Electrical Engineering, Computer Science, Applied Mathematics.  Expectation is that degree will be obtained by July 2024 or earlier." 💀

**Comment by RonLek** [comment]
That’s okay right? Multiple if not majority are grad students.

**Comment by Mazzaleen** [comment]
idts- kinda different from all the previous roles being new grad openings requiring undergraduate degree.

**Comment by AdityaPune** [comment]
Aren't there already a bunch of PhD only roles posted?
What's wrong with Master's only roles.

**Comment by harsh4799** [comment]
Yes, please add masters roles ! There are a lot of us that use this repository for applying to full time jobs

**Pull request closed without merging**
