### PR TITLE
Multiple New Grad Positions have been closed

### PR DESCRIPTION
**Pull request by Sumer16**
Multiple new grad positions have been closed either due to the position being filled or the role has been canceled.

NOTE: Some of them still have at least one of the New Grad roles open.

Companies mentioned in this commit:
- Cognex
- Bloomberg Industry Group
- Capital One
- Nextdoor
- Georgia Tech Research Institute
- United Airlines
- Thomson Reuters
- Everi
- Aveva
- Netsmart
- Salesforce
- UT Austin
- Manulife
- Cadence
- NXP
- ServiceNow
- FactSet
- ICF
- Wellington Management
- Blue Origin
- Okta
- Glean
- GEICO
- Disco
- Ascend Analytics
- Ciena
- F5
- Bloom Energy
- Guidehouse
- General Motors
- John Hancock
- Polaris
- Capgemini
- Chevron
- Tencent

### CODE REVIEW

**Review by shrey82 — APPROVED** [review]

**Review by shrey82 — APPROVED** [review]
LGTM!

**Review by ReaVNaiL — APPROVED** [review]

**Comment by ReaVNaiL** [comment]
Actually many of these are open why are we closing them?

**Comment by Sumer16** [comment]
Can you point out which ones?

**Comment by Sumer16** [comment]
When I was looking at them on Friday night many of the Workday ones where closed.

**Comment by ReaVNaiL** [comment]
I see, probably might've been a workday issue. I'm currently going through them and updating them.

**Comment by Sumer16** [comment]
I'm making a new PR for this

**Comment by ReaVNaiL** [comment]
I think we can keep it here, I'm almost done with the edits, 👍

**Comment by ReaVNaiL** [comment]
I'll reopen it for now.

**Comment by Sumer16** [comment]
That's fine I will open a new PR its much easier.

**Pull request closed without merging**
