### PR TITLE
Added Palo Alto Networks New Grad roles

### PR DESCRIPTION
**Pull request by Sumer16**

### CODE REVIEW

**Comment by hvnguyen57** [comment]
image
these positions are for "Staff Software Engineer"

**Comment by Sumer16** [comment]
Yeah, I was a bit confused too but these positions are listed under their early careers page for new grads.

**Comment by ReaVNaiL** [comment]
All except the Systems Engineer one seem to be new grad roles, in the experience section they would include something similar to this: 

```
Your Experience 

    Bachelor's degree earned recently or anticipated to be earned within the next 12 months in Machine Learning, Computer Science, Cybersecurity, Data Science, Artificial Intelligence, Software Engineering or something similar 
    Strong programming skills 
```

But the Systems Engineer one doesn't have that.

**Comment by SoumyaMukhija** [comment]
All roles have “ Requirements – To apply, you must have the authorization to work within the United States” in them. Please add that.

**Comment by hvnguyen57** [comment]
ok everything looks fine to me based off of previous discussion; i'll approve and merge

**Review by hvnguyen57 — APPROVED** [review]

**Pull request merged**
